apiVersion: v1
kind: Service
metadata:
  name: events-app-service
  namespace: default
  labels:
    app: events-app
spec:
  selector:
    app: events-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
    - name: app-port
      port: 8083
      targetPort: 8083
      nodePort: 30001
      protocol: TCP
  type: NodePort