apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-app
resources:
  - namespace.yaml
  - nginx-deployment.yaml
  - nginx-service-clusterip.yaml
  - nginx-service-loadbalancer.yaml
  - ingress.yaml
commonLabels:
  app: nginx
  environment: production